project:
  type: website

website:
  description: "Peter's Pumpkin Carvings"
  site-url: https://peterspumpkinpatch.org
  title: "Peter's Pumpkin Patch"
  favicon: _favicon/favicon.ico
  open-graph: true
  twitter-card: true
  navbar:
    background: black
    left: 
      - text: "This Year's Patch"
        href: pumpkins/2025
      - text: "Pumpkins"
        href: pumpkins
      - text: "Non-Pumpkins"
        href: non-pumpkins
      - text: "Browse All"
        href: all-carvings
    # right:
    #   - icon: instagram
    #     href: https://instagram.com/
    #   - icon: twitter-x
    #     href: https://x.com
  page-footer: 
    background: $footer-bg
    left: "&#169; 2004 -- 2026 Peter T. Wiegand"
    right: "Website by [Connor T. Wiegand](https://github.com/connortwiegand/){target='_blank'} <br/> Made with [Quarto](https://quarto.org/) | [Source code](https://github.com/jacklego/jacklego.github.io){target='blank'}"
  


format:
  html:
    theme: [darkly, sass/theme.scss]
    fontcolor: $body-color
    lightbox: true
    canonical-url: true

# pthemes:
#   2025: Classic Movie Monsters


# website:
  # announcement: 
  #   icon: cone-striped
  #   dismissable: true
  #   content: "This website is currently under construction. To view the original site, visit [jacklego2.wixsite.com/peter-spumpkinpatch](https://jacklego2.wixsite.com/peter-spumpkinpatch)"
  #   type: success
  #   position: above-navbar