#!/usr/bin/env python3
"""Gate year visibility off `_variables.yml`.

A year directory under `pumpkins/` is public iff `_variables.yml` lists a
`ptheme` key for it AND that year is <= `currentYear`. Every other year gets a
generated `pumpkins/<year>/_metadata.yml` carrying `draft: true`, which every
carving page beneath it inherits. Combined with `draft-mode: unlinked` in
`_quarto.yml`, those pages still render at their real URLs -- so Peter can
review them -- but are excluded from listings, the sitemap, search, and the feed.

Going live is therefore two edits to `_variables.yml` and a re-render.

This runs as a Quarto `pre-render` script, so it is deliberately stdlib-only:
Quarto invokes it with whatever `python3` is on PATH, and it must not need a
virtualenv. `_variables.yml` is a flat file of scalars, so it is read with a
small parser rather than PyYAML.

Usage: python3 scripts/sync_drafts.py [--check] [--quiet]
  --check   report what would change and exit 1 if anything would, without
            writing. Use in CI to catch a `_variables.yml` edit that was never
            synced.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
VARIABLES = ROOT / "_variables.yml"
PUMPKINS = ROOT / "pumpkins"

MARKER = "# Generated by scripts/sync_drafts.py -- do not edit by hand."
DRAFT_FILE = f"""{MARKER}
#
# This season is not public yet. `draft: true` is inherited by every carving
# page in this directory; with `draft-mode: unlinked` in _quarto.yml the pages
# render at their real URLs but are absent from listings, the sitemap, search,
# and the feed.
#
# To publish it: add a `ptheme` entry for {{year}} in _variables.yml and set
# `currentYear: {{year}}`. This file then disappears on the next render.

draft: true
"""


def read_variables(path: Path) -> tuple[int | None, set[str]]:
    """Pull `currentYear` and the `ptheme` keys out of _variables.yml.

    Handles exactly the shape that file has: top-level scalars plus one nested
    block of `<year>: <theme>` entries.
    """
    current: int | None = None
    themes: set[str] = set()
    in_ptheme = False
    for raw in path.read_text(encoding="utf-8").splitlines():
        line = raw.rstrip()
        if not line or line.lstrip().startswith("#"):
            continue
        indented = line[0] in " \t"
        if not indented:
            in_ptheme = line.split(":", 1)[0].strip() == "ptheme"
            m = re.match(r"currentYear\s*:\s*(\d{4})", line)
            if m:
                current = int(m.group(1))
            continue
        if in_ptheme:
            m = re.match(r"\s+(\d{4})\s*:", line)
            if m:
                themes.add(m.group(1))
    return current, themes


def is_public(year: str, current: int | None, themes: set[str]) -> bool:
    if year not in themes:
        return False
    return current is None or int(year) <= current


def desired(year: str) -> str:
    return DRAFT_FILE.format(year=year)


def main() -> int:
    check = "--check" in sys.argv
    quiet = "--quiet" in sys.argv

    if not VARIABLES.exists():
        print(f"{VARIABLES} not found", file=sys.stderr)
        return 2
    current, themes = read_variables(VARIABLES)

    changes = []
    for year_dir in sorted(p for p in PUMPKINS.glob("[0-9][0-9][0-9][0-9]") if p.is_dir()):
        year = year_dir.name
        meta = year_dir / "_metadata.yml"
        public = is_public(year, current, themes)

        if public:
            if not meta.exists():
                continue
            body = meta.read_text(encoding="utf-8")
            if MARKER in body:
                changes.append(("publish", year, meta, None))
            elif re.search(r"^draft\s*:\s*true\s*$", body, re.MULTILINE):
                stripped = re.sub(
                    r"^draft\s*:\s*true\s*\n?", "", body, flags=re.MULTILINE
                )
                changes.append(("unstamp", year, meta, stripped))
            continue

        want = desired(year)
        if not meta.exists():
            changes.append(("gate", year, meta, want))
        elif MARKER in meta.read_text(encoding="utf-8"):
            if meta.read_text(encoding="utf-8") != want:
                changes.append(("refresh", year, meta, want))
        else:
            body = meta.read_text(encoding="utf-8")
            if not re.search(r"^draft\s*:\s*true\s*$", body, re.MULTILINE):
                changes.append(("stamp", year, meta, body.rstrip() + "\n\ndraft: true\n"))

    if not changes:
        if not quiet:
            live = sorted(y for y in themes if is_public(y, current, themes))
            print(f"drafts in sync (public: {', '.join(live) or 'none'})")
        return 0

    for action, year, path, body in changes:
        rel = path.relative_to(ROOT)
        verb = {
            "gate": "gate as draft",
            "refresh": "refresh draft marker",
            "stamp": "add draft: true to existing",
            "publish": "publish (remove)",
            "unstamp": "publish (strip draft: true from)",
        }[action]
        print(f"{'would ' if check else ''}{verb}: {rel}")
        if check:
            continue
        if body is None:
            path.unlink()
        else:
            path.write_text(body, encoding="utf-8")

    return 1 if check else 0


if __name__ == "__main__":
    sys.exit(main())
